name: AutoKickAura
version: 1.0.0
main: pdm\Main
api: [5.0.0]
author: PDevChris
commands:
  auradetector:
    description: Command to reload the plugin configuration.
    usage: /<command> reload
    permission: auradetector.reload
    permission-message: "You do not have permission to reload the plugin configuration."
permissions:
  auradetector.reload:
    description: Allows a user to reload the plugin configuration.
    default: op
  auradetector.kick:
    description: Allows a user to manually kick players for suspected hacks.
    default: op
  auradetector.notify:
    description: Allows a user to receive hack detection notifications.
    default: op
