name: AutoKickAura
version: 1.0.0
main: pdm\Main
api: [5.0.0]
author: PDevChris
commands:
  auradetector:
    description: Reloads the plugin configuration.
    usage: /<command> reload
permissions:
  auradetector.reload:
    description: Allows a user to reload the plugin configuration.
    default: op
  auradetector.notify:
    description: Allows the player to receive notifications about hack detections.
    default: op
config:
  kick_threshold: 3  # Number of kicks before a player gets banned.
  ban_threshold: 0  # Set to 0 if bans should be immediate after the first offense.
  ban_duration: 6  # Duration of the ban in days.
  kick_message: "You have been kicked for using hacks!"
  ban_message: "You have been banned for using Aura!"
  notify_staff_on_detection: true  # Whether staff members should be notified when a player is caught.
  staff_notify_message: "Player {player} was detected using hacks and has been kicked/banned."
  enable_hitbox_detection: true  # Whether Hitbox hack detection is enabled.
  enable_autoaura_detection: true  # Whether AutoAura hack detection is enabled.
  enabled: true  # Whether the hack detection is enabled or not.
