# Plugin Configuration for AutoKickAura

# Enable or disable AutoAura detection
autoaura_enabled: true

# Enable or disable Hitbox detection
hitbox_enabled: true

# The number of kicks before a player is banned (set to 0 to disable)
kick_threshold: 3  # Number of kicks before a player gets banned.

# Duration of ban in days (used only if ban is enabled)
ban_duration: 6  # 6 days duration for the ban.

# Message to show when a player is kicked for AutoAura
autoaura_kick_message: "You have been kicked for using AutoAura!"

# Message to show when a player is kicked for Hitbox
hitbox_kick_message: "You have been kicked for using Hitbox!"

# Message to show when a player is banned for using hacks
ban_message: "You have been banned for using hacks!"

# If true, staff members will be notified when a player is detected using hacks
notify_staff_on_detection: true

# The message that will be sent to staff when a player is detected using hacks
staff_notify_message: "Player {player} was detected using hacks and has been kicked/banned."

# General plugin status (true means the plugin is active)
enabled: true
