# Plugin Configuration for AutoKickAura

# Enable or disable AutoAura detection
autoAuraEnabled: true

# Enable or disable Hitbox detection
hitboxEnabled: true

# The number of warnings before a player gets kicked
kick_threshold: 3

# Ban duration in hours (set to 0 for no banning, only kicking)
ban_duration: 6

# Messages displayed to the player
messages:
  auto_aura_kick: "AutoAura detected! You have been kicked."
  hitbox_kick: "Hitbox hack detected! You have been kicked."
  warning_message: "Warning! {reason} ({remaining} warnings left before kick)"

# Debugging options
debug: false
